import { useState, useEffect } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Save, ChevronLeft } from 'lucide-react'
import { devotionalsApi } from '@/lib/supabase'
import Button from '@/components/ui/Button'
import Card from '@/components/ui/Card'

export default function EditDevotionalPage() {
  const { id } = useParams<{ id: string }>()
    const navigate = useNavigate()
      const [saving, setSaving] = useState(false)
        const [loading, setLoading] = useState(true)

          const [form, setForm] = useState({
              title: '',
                  bible_reference: '',
                      bible_text: '',
                          devotional_text: '',
                              final_prayer: '',
                                  status: 'draft' as 'draft' | 'published' | 'scheduled',
                                      publish_date: new Date().toISOString().slice(0, 16),
                                          send_notification: false,
                                            })

                                              useEffect(() => {
                                                  if (!id) return
                                                      devotionalsApi.getById(id).then(({ data, error }) => {
                                                            if (error || !data) { alert('Devocional nao encontrado.'); navigate('/admin/devocionais'); return }
                                                                  setForm({
                                                                          title: data.title ?? '',
                                                                                  bible_reference: data.bible_reference ?? '',
                                                                                          bible_text: data.bible_text ?? '',
                                                                                                  devotional_text: data.devotional_text ?? '',
                                                                                                          final_prayer: data.final_prayer ?? '',
                                                                                                                  status: data.status as 'draft' | 'published' | 'scheduled',
                                                                                                                          publish_date: data.publish_date ? new Date(data.publish_date).toISOString().slice(0, 16) : new Date().toISOString().slice(0, 16),
                                                                                                                                  send_notification: data.send_notification ?? false,
                                                                                                                                        })
                                                                                                                                              setLoading(false)
                                                                                                                                                  })
                                                                                                                                                    }, [id, navigate])

                                                                                                                                                      const updateForm = (key: string, value: unknown) => setForm(f => ({ ...f, [key]: value }))

                                                                                                                                                        const handleSave = async () => {
                                                                                                                                                            if (!id) return
                                                                                                                                                                setSaving(true)
                                                                                                                                                                    try {
                                                                                                                                                                          const { error } = await devotionalsApi.update(id, {
                                                                                                                                                                                  ...form,
                                                                                                                                                                                          publish_date: new Date(form.publish_date).toISOString(),
                                                                                                                                                                                                })
                                                                                                                                                                                                      if (error) throw error
                                                                                                                                                                                                            alert('Devocional atualizada!')
                                                                                                                                                                                                                  navigate('/admin/devocionais')
                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                            console.error(err)
                                                                                                                                                                                                                                  alert('Erro ao salvar.')
                                                                                                                                                                                                                                      } finally {
                                                                                                                                                                                                                                            setSaving(false)
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                    if (loading) return <div className="flex items-center justify-center h-48"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-700" /></div>

                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                          <div className="max-w-xl mx-auto space-y-5">
                                                                                                                                                                                                                                                                <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                        <button onClick={() => navigate('/admin/devocionais')} className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-500"><ChevronLeft size={20} /></button>
                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                          <h1 className="text-xl font-bold text-gray-900">Editar devocional</h1>
                                                                                                                                                                                                                                                                                                    <p className="text-gray-500 text-sm mt-0.5">Altere os campos e salve</p>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                        <Card padding="md" className="space-y-4">
                                                                                                                                                                                                                                                                                                                                <h2 className="font-semibold text-gray-800">Conteudo</h2>
                                                                                                                                                                                                                                                                                                                                        {(['title', 'bible_reference'] as const).map(key => (
                                                                                                                                                                                                                                                                                                                                                  <div key={key}>
                                                                                                                                                                                                                                                                                                                                                              <label className="block text-sm font-medium text-gray-700 mb-1">{key === 'title' ? 'Titulo *' : 'Versiculo base *'}</label>
                                                                                                                                                                                                                                                                                                                                                                          <input type="text" value={form[key]} onChange={e => updateForm(key, e.target.value)} className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:border-primary-400" />
                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                    {([['bible_text','Texto biblico',3],['devotional_text','Mensagem *',6],['final_prayer','Oracao final',3]] as [string,string,number][]).map(([key,label,rows]) => (
                                                                                                                                                                                                                                                                                                                                                                                                              <div key={key}>
                                                                                                                                                                                                                                                                                                                                                                                                                          <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <textarea value={form[key as keyof typeof form] as string} onChange={e => updateForm(key, e.target.value)} rows={rows} className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:border-primary-400 resize-none" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Card padding="md" className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="font-semibold text-gray-800">Publicacao</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select value={form.status} onChange={e => updateForm('status', e.target.value)} className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:border-primary-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="draft">Rascunho</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="published">Publicada</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="scheduled">Agendada</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Button variant="gold" size="lg" fullWidth loading={saving} icon={<Save size={16} />} onClick={handleSave}>Salvar alteracoes</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }